---
- name: "Configuring ~/.bashrc"
  hosts: all
  tasks:
    - name: create ~/.kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0744'

    - name: add ~/.local/bin to PATH
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export PATH="$PATH:~/.local/bin"'
        line: 'export PATH="$PATH:~/.local/bin"'
        state: present
        backup: true

    - name: export KUBECONFIG variable
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export KUBECONFIG.*'
        line: 'export KUBECONFIG=~/.kube/config'
        state: present
        backup: true

    - name: export KREW_ROOT variable
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'
        line: 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'
        state: present
        backup: true

    - name: add kubectl completion
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^source <(kubectl completion bash)'
        line: 'source <(kubectl completion bash)'
        state: present
        backup: true

    - name: add complete -F __start_kubectl k
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^complete -F __start_kubectl k'
        line: 'complete -F __start_kubectl k'
        state: present
        backup: true

    - name: add alias
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^{{ item }}'
        line: '{{ item }}'
        state: present
        backup: true
      with_items:
        - "alias k=kubectl"
        - "alias kns=kubectl-ns"
        - "alias kctx=kubectl-ctx"
